services:
  db:
    image: mongo
    container_name: remix-expensify-db
    restart: always
    ports:
      - 27027:27017
    volumes:
      - expensify-db:/data/db
    env_file:
      - ./.env.local

volumes:
  expensify-db:
